Feature 167175 report web api
Flexberry/NewPlatform.Flexberry.Analytics pull request #4
Opened 2019-06-04 12:17 UTC by NSelivanov

Создал WebApi для работы с отчетами.

2019-06-24 11:12 UTC, mao29 requested changes

2019-06-24 11:12 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/Abstractions/IReportManager.cs
> +        Task<int> GetReportPageCount(string reportPath, JObject parameters, CancellationToken ct);
В методе формирования отчета параметры в виде Dictionary. Предлагаю сделать единообразно

2019-06-24 11:12 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/PentahoReport/PentahoReportManager.cs
> +                Timeout = Timeout.InfiniteTimeSpan
Предлагаю вынести в конфиг и если не указан или 0 использовать Infinite

2019-06-24 11:12 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/PentahoReport/PentahoReportManager.cs
> +                return;
Поди исключение надо генерировать. И почему endpoing не проверяется?

2019-06-24 11:12 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/PentahoReport/PentahoReportManager.cs
> +        /// <param name="parameters">Параметры отчёта.</param>
Не хватает одного аргумента в комментарии

2019-06-24 11:12 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/PentahoReport/PentahoReportManager.cs
> +        private string GetRequestBody(JObject parameters)
Метод похож на GetReportUri, но логика отличается. Может один в другом поиспользовать?

2019-06-24 11:12 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/PentahoReport/PentahoReportManager.cs
> +            string reportHtml = await response.Content.ReadAsStringAsync();
Сюда ct не надо передавать?

2019-06-24 11:12 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/PentahoReport/PentahoReportManager.cs
> +            return $"{reportHtml}<style>{css}</style>";
Для ускорения рендеринга обычно стили до разметки пытаются вставить

2019-06-24 11:12 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/PentahoReport/PentahoReportManager.cs
> +        public string GetReportParameters(string reportPath)
А что за метод вообще такой? Он не просто queryString получать должен?

2019-06-24 11:12 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/PentahoReport/PentahoReportManager.cs
> +                    byte[] bytes = await response.Content.ReadAsByteArrayAsync();
ct не надо передавать?

2019-06-24 11:12 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/ReportWebApiService/App_Start/UnityConfig.cs
> +            container.RegisterInstance<IReportManager>(new PentahoReportManager());
Не нужно регистрировать экземпляр. Нужно зарегистрировать просто маппинг на PentahoReportManager.

2019-06-24 11:12 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/ReportWebApiService/Controllers/ReportController.cs
> +            string reportPath = parameters[reportPathParamName].ToString();
NullReferenceException не может быть?

2019-06-25 05:00 UTC, NicholasNoise commented on NewPlatform.Flexberry.Analytics/Abstractions/Abstractions.csproj
> +    <AssemblyName>Abstractions</AssemblyName>
Изменить имя сборки и имя корневого пространства имён.

2019-06-25 05:00 UTC, NicholasNoise commented on NewPlatform.Flexberry.Analytics/PentahoReport/PentahoReportManager.cs
> +        /// <param name="parameters">Параметры отчёта.</param>
Заменить на `/// <inheritdoc />`.

2019-06-25 05:01 UTC, NicholasNoise commented on NewPlatform.Flexberry.Analytics/Abstractions/Abstractions.csproj
> +    <AssemblyName>Abstractions</AssemblyName>
А ещё добавить подпись сборкам, ес-но

2019-06-26 06:49 UTC, KollegOFF reviewed
Можно добавить пакет `StyleCop.Analyzers`, [как здесь](https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService/blob/develop/NewPlatform.Flexberry.ORM.ODataService/packages.config#L21).

2019-07-31 11:24 UTC, mao29 requested changes

2019-07-31 11:24 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/PentahoReport/PentahoReportManager.cs
> +                throw new NullReferenceException();
Нужно пробрасывать ArgumentNullException для конкретного параметра. NullReferenceException вообще не для этого

2019-07-31 11:24 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/PentahoReport/PentahoReportManager.cs
> +        private readonly HttpClient PentahoHttpClient;
внутренние поля именуются в _camelCase

2019-07-31 11:24 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/PentahoReport/PentahoReportManager.cs
> +            throw new NotImplementedException();
Почему в дефолтной имплементации что-то осталось не реализовано? Либо это не нужно и можно из интерфейса удалить, либо надо реализовать

2019-07-31 11:24 UTC, mao29 commented on NewPlatform.Flexberry.Analytics/ReportWebApiService/Controllers/ReportController.cs
> +            string reportPath = parameters.GetValue(reportPathParamName)?.ToString();
Код валидации проверки параметра reportPath дублируется во всех методах. Предлагаю вынести в приватный метод

2019-07-31 14:48 UTC, NicholasNoise requested changes

2019-07-31 14:48 UTC, NicholasNoise commented on NewPlatform.Flexberry.Analytics/ReportWebApiService/App_Start/UnityConfig.cs
> +namespace NewPlatform.Flexberry.Analytics.WebApi
Удалить файл.

2019-07-31 14:48 UTC, NicholasNoise commented on NewPlatform.Flexberry.Analytics/ReportWebApiService/App_Start/UnityWebApiActivator.cs
> +namespace NewPlatform.Flexberry.Analytics.WebApi
Удалить.

2019-07-31 14:48 UTC, NicholasNoise commented on NewPlatform.Flexberry.Analytics/ReportWebApiService/App_Start/WebApiConfig.cs
> +namespace NewPlatform.Flexberry.Analytics.WebApi
Удалить.

2019-07-31 14:48 UTC, NicholasNoise commented on NewPlatform.Flexberry.Analytics/ReportWebApiService/Global.asax.cs
> +namespace NewPlatform.Flexberry.Analytics.WebApi
Удалить.

2019-07-31 14:48 UTC, NicholasNoise commented on NewPlatform.Flexberry.Analytics/ReportWebApiService/Web.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
Удалить вместе с трансформациями.

2019-07-31 14:48 UTC, NicholasNoise commented on .gitattributes
> +* text=auto
lf

2019-07-31 14:49 UTC, NicholasNoise commented on NewPlatform.Flexberry.Analytics/ReportWebApiService/packages.config
> +  <package id="log4net" version="2.0.3" targetFramework="net45" />
Оставить только используемые пакеты.

2019-08-08 14:22 UTC, mao29 approved these changes

2019-09-02 08:11 UTC, bratchikov requested changes

2019-09-02 08:11 UTC, bratchikov commented on NewPlatform.Flexberry.Analytics/Abstractions/NewPlatform.Flexberry.Analytics.Abstractions.csproj
> +    <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
Почему именно 4.5.2?

2019-09-02 08:11 UTC, bratchikov commented on NewPlatform.Flexberry.Analytics/Abstractions/NewPlatform.Flexberry.Analytics.Abstractions.nuspec
> +    <version>1.0.0</version>
1.0.0-beta01

2019-09-02 08:11 UTC, bratchikov commented on NewPlatform.Flexberry.Analytics/Abstractions/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2018")]
New Platform Ltd 2019

2019-09-02 08:11 UTC, bratchikov commented on NewPlatform.Flexberry.Analytics/Pentaho/NewPlatform.Flexberry.Analytics.Pentaho.nuspec
> +    <version>1.0.0</version>
1.0.0-beta01

2019-09-02 08:11 UTC, bratchikov commented on NewPlatform.Flexberry.Analytics/Pentaho/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2018")]
New Platform Ltd 2019

2019-09-02 08:11 UTC, bratchikov commented on NewPlatform.Flexberry.Analytics/WebAPI/Controllers/ReportController.cs
> +﻿using ICSSoft.STORMNET;
using-и внутри namespace

2019-09-02 08:11 UTC, bratchikov commented on NewPlatform.Flexberry.Analytics/WebAPI/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2019")]
New Platform Ltd

2019-09-02 08:11 UTC, bratchikov commented on NewPlatform.Flexberry.Analytics/WebAPI/Properties/AssemblyInfo.cs
> +[assembly: AssemblyTrademark("")]
Flexberry

2019-09-02 08:11 UTC, bratchikov commented on NewPlatform.Flexberry.Analytics/WebApiSample/App_Start/WebApiConfig.cs
> +﻿using NewPlatform.Flexberry.AspNet.WebApi.Cors;
using-и внутри namespace

2019-09-02 08:11 UTC, bratchikov commented on NewPlatform.Flexberry.Analytics/WebApiSample/Global.asax.cs
> +using NewPlatform.Flexberry.Analytics.WebAPI;
using-и внутри namespace

2019-09-02 08:11 UTC, bratchikov commented on NewPlatform.Flexberry.Analytics/WebApiSample/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2019")]
New Platform Ltd

2019-09-03 10:25 UTC, NicholasNoise commented on NewPlatform.Flexberry.Analytics/Abstractions/NewPlatform.Flexberry.Analytics.Abstractions.nuspec
> +      <group targetFramework=".NETFramework4.5.2">
А тут поправить версию .net?

2019-09-03 10:26 UTC, NicholasNoise commented on NewPlatform.Flexberry.Analytics/Abstractions/NewPlatform.Flexberry.Analytics.Abstractions.nuspec
> +    <file src="bin\Debug\NewPlatform.Flexberry.Analytics.Abstractions.dll" target="lib\net452\NewPlatform.Flexberry.Analytics.Abstractions.dll" />
тут тоже

2019-09-03 10:30 UTC, NicholasNoise commented on NewPlatform.Flexberry.Analytics/WebAPI/ApiConfig/ReportApiConfig.cs
> +﻿namespace NewPlatform.Flexberry.Analytics.WebAPI
Удалить файл.

2019-09-03 10:30 UTC, NicholasNoise commented on NewPlatform.Flexberry.Analytics/Pentaho/PentahoReportManager.cs
> +            if (ct.IsCancellationRequested == true)
Божественная конструкция

2019-09-03 10:39 UTC, NSelivanov commented on NewPlatform.Flexberry.Analytics/Pentaho/PentahoReportManager.cs
> +            if (ct.IsCancellationRequested == true)
Можно по конкретнее... Что именно не так?

2019-09-04 11:44 UTC, bratchikov approved these changes

2019-09-04 11:45 UTC, merged